import torch
import torch.nn as nn
import torch.nn.functional as F


class STArgmaxSoftmaxGeneric(nn.Module):
    """Straight-Through Estimator for Argmax with Softmax gradients.

    Forward pass computes ``argmax(softmax(logits))`` while the backward pass
    flows gradients through ``softmax(logits)``, enabling gradient-based
    optimization of discrete sequences.

    Args:
        onehot_dim: Number of classes in the one-hot dimension.
    """

    def __init__(self, onehot_dim: int) -> None:
        super().__init__()
        self.onehot_dim = onehot_dim

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply straight-through argmax-softmax to logits.

        Args:
            x: Logits tensor of shape ``(batch, onehot_dim, length)``.

        Returns:
            One-hot tensor with same shape as input. Forward pass is discrete
            (argmax), backward pass has softmax gradients.
        """
        softmax_seq = F.softmax(x, dim=1)
        argmax_seq = 1.0 * F.one_hot(torch.argmax(softmax_seq, 1), self.onehot_dim).permute(
            [0, 2, 1]
        )
        # softmax.detach() breaks gradient flow; adding it back restores gradients
        return argmax_seq - softmax_seq.detach() + softmax_seq


class Translator(nn.Module):
    """Differentiable nucleotide-to-protein translation with convolutional filters.

    Enables gradient flow from protein-level loss functions back to nucleotide
    sequences. Processes all 6 possible reading frames (3 frames x 2 strands):

    1. 3nt convolutional filters extract "codon" features
    2. 3 reading frames generated by shifting codon features (+0, +1, +2)
    3. Convolutional filters map "codons" to amino acids (forward and reverse strands)
    4. Straight-through estimation for discrete amino acid sampling

    Args:
        n_channel: Number of intermediate channels for codon features.
            Higher values (>512) tend to produce better gradients.
    """

    def __init__(self, n_channel: int = 1024) -> None:
        super().__init__()
        self.n_channel = n_channel
        self.n_nuc = 4  # ACGT
        self.n_aa = 21  # 20 AA + stop

        # Kernel size=3 for triplet codons, stride=1 for sliding window
        self.codon = nn.Conv1d(self.n_nuc, self.n_channel, kernel_size=3, stride=1, bias=False)
        # Kernel size=1 for codon-to-AA mapping; stride=3 for non-overlapping triplets
        self.aa_withstop_f = nn.Conv1d(
            self.n_channel, self.n_aa, kernel_size=1, stride=3, bias=False
        )
        self.aa_withstop_r = nn.Conv1d(
            self.n_channel, self.n_aa, kernel_size=1, stride=3, bias=False
        )
        self.stargsoftmax_withstop = STArgmaxSoftmaxGeneric(self.n_aa)

    def forward(
        self,
        input: torch.Tensor,
        temperature: float = 1.0,
    ) -> list[torch.Tensor]:
        """Translate nucleotide sequences to amino acid sequences in all 6 frames.

        Args:
            input: One-hot encoded nucleotide sequence of shape
                ``(batch, 4, seq_length)``.
            temperature: Sampling temperature for the straight-through estimator.

        Returns:
            List of 6 tensors, each of shape ``(batch, 21, protein_length)``:
                - Indices 0-2: Forward strand, reading frames +0, +1, +2
                - Indices 3-5: Reverse strand, reading frames -0, -1, -2

                where ``protein_length = (seq_length - frame_offset - 2) // 3``.
        """
        codon = self.codon(input)
        codon_frames = [codon, codon[:, :, 1:], codon[:, :, 2:]]
        aa_withstop = [self.aa_withstop_f(c) for c in codon_frames] + [
            self.aa_withstop_r(c) for c in codon_frames
        ]
        aa_withstop_temperature = [aa * temperature for aa in aa_withstop]
        return [self.stargsoftmax_withstop(aa) for aa in aa_withstop_temperature]


class Optimus(nn.Module):
    """Optimus 5' UTR MRL prediction model (PyTorch re-implementation).

    Re-implementation of the Optimus model from `Sample et al.`_ with minor
    architecture modifications: shared convolution weights with multiple dense
    heads for joint training on all datasets.

    .. _Sample et al.:
        https://github.com/pjsample/human_5utr_modeling

    Args:
        inp_len: Input sequence length (50 or 100 in Optimus).
        nbr_filters: Number of convolutional filters (120 in Optimus).
        filter_len: Convolutional filter length (8 in Optimus).
        border_mode: Padding mode for convolutions ('same' in Optimus).
        dropout1: Dropout rate after second conv layer (0.0 in Optimus).
        dropout2: Dropout rate after third conv layer (0.0 in Optimus).
        dropout3: Dropout rate in dense head (0.2 in Optimus).
        nodes: Number of hidden units in dense head (40 in Optimus).
        out_kw: List of output keywords/names for each prediction head.
        n_out_col: Number of output units per prediction head.
    """

    def __init__(
        self,
        inp_len: int,
        nbr_filters: int,
        filter_len: int,
        border_mode: int | str,
        dropout1: float,
        dropout2: float,
        dropout3: float,
        nodes: int,
        out_kw: list[str],
        n_out_col: int,
    ) -> None:
        super().__init__()
        self.n_out = len(out_kw)
        self.out_ind = {k: v for v, k in enumerate(out_kw)}

        self.conv = nn.Sequential(
            nn.Conv1d(4, nbr_filters, filter_len, padding=border_mode),
            nn.ReLU(),
            nn.Conv1d(nbr_filters, nbr_filters, filter_len, padding=border_mode),
            nn.ReLU(),
            nn.Dropout(dropout1),
            nn.Conv1d(nbr_filters, nbr_filters, filter_len, padding=border_mode),
            nn.ReLU(),
            nn.Dropout(dropout2),
        )

        with torch.no_grad():
            dummy_input = torch.zeros(1, 4, inp_len)
            x = self.conv(dummy_input)
            self.conv_output_size = x.shape[1] * x.shape[2]

        self.head = nn.ModuleList(
            [
                nn.Sequential(
                    nn.Flatten(),
                    nn.Linear(self.conv_output_size, nodes),
                    nn.ReLU(),
                    nn.Dropout(dropout3),
                    nn.Linear(nodes, n_out_col),
                )
                for _ in range(self.n_out)
            ]
        )

    def forward(
        self,
        x: torch.Tensor,
        final_ind: int = 0,
        final_kw: str | None = None,
    ) -> torch.Tensor:
        """Run forward pass through shared convolutions and a selected head.

        Args:
            x: One-hot sequence tensor of shape ``(batch, 4, seq_length)``.
            final_ind: Index of the prediction head. Ignored if ``final_kw``
                is provided.
            final_kw: Keyword name of the prediction head. Takes precedence
                over ``final_ind`` if both are provided.

        Returns:
            Prediction tensor of shape ``(batch, n_out_col)``.
        """
        x = self.conv(x)

        if final_kw is not None:
            x = self.head[self.out_ind[final_kw]](x)
        elif final_ind is not None:
            x = self.head[final_ind](x)

        return x


class OptimusOLG(nn.Module):
    """Differentiable 5' UTR optimizer for dual expression from overlapping genes.

    SeqProp-style algorithm (`Bogard et al. 2019`_) that optimizes nucleotide
    sequences for dual MRL from alternative start codons while constraining
    the encoded protein sequence.

    .. _Bogard et al. 2019: https://doi.org/10.1186/s12859-021-04437-5

    Pipeline:
        1. Normalized weights => logits for sampling nucleotide sequences
        2. Force start codon at the specified position
        3. Returns two MRLs (one per reading frame) and the amino acid sequence
           for the overlapping region

    Args:
        device: Compute device (CPU/GPU).
        model: Optimus 5' model for MRL prediction.
        translator: Nucleotide-to-amino-acid translation module.
        num_batch: Number of sequences to optimize in parallel.
        seq_length: Total length of each nucleotide sequence.
        alt_start: Position where the start codon is inserted (0-based index of A).
        start_codon: One-hot encoded start codon of shape ``(batch, 4, 3)``.
        right_overhang_mask: Boolean mask for right overhang region.
        seed_onehot: Optional seed sequence as one-hot tensor of shape
            ``(batch, 4, seq_length)``. If provided, biases sampling toward
            the seed sequence.
        model_input_len: Expected input length for the Optimus model. Sequences
            shorter than this are left-padded with zeros before MRL prediction.
    """

    def __init__(
        self,
        device: torch.device,
        model: nn.Module,
        translator: nn.Module,
        num_batch: int,
        seq_length: int,
        alt_start: int,
        start_codon: torch.Tensor,
        right_overhang_mask: torch.Tensor,
        seed_onehot: torch.Tensor | None = None,
        model_input_len: int = 100,
    ) -> None:
        super().__init__()

        self.stsampler = STArgmaxSoftmaxGeneric(4)
        self.model = model
        self.translator = translator
        self.num_batch = num_batch
        self.onehot_dim = 4
        self.seq_length = seq_length
        self.model_input_len = model_input_len
        self.alt_start = alt_start
        self.aa_len = (self.seq_length - self.alt_start) // 3 - 1
        self.device = device
        self.eps = 1e-8
        self.mask_val = -1e8

        self.weight = nn.Parameter(torch.zeros(self.num_batch, self.onehot_dim, self.seq_length))
        self.seed_onehot = seed_onehot
        if self.seed_onehot is None:
            torch.nn.init.xavier_normal_(self.weight)

        self.layer_norm_seed_left = nn.LayerNorm((self.onehot_dim, self.alt_start))
        self.layer_norm_seed_right = nn.LayerNorm(
            (self.onehot_dim, self.seq_length - self.alt_start)
        )
        self.layer_norm_left = nn.LayerNorm((self.onehot_dim, self.alt_start))
        self.layer_norm_right = nn.LayerNorm((self.onehot_dim, self.seq_length - self.alt_start))

        self.model.eval()
        self.translator.eval()

        self.start_codon = start_codon.to(torch.float32).to(self.device)
        self.right_overhang_mask = right_overhang_mask.to(self.device)
        self.right_end = self.seq_length - self.right_overhang_mask.shape[-1]

    def forward(
        self,
        input_onehot: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """Generate or process sequences and predict MRL + protein.

        Args:
            input_onehot: Optional pre-computed one-hot nucleotide sequences
                of shape ``(batch, 4, seq_length)``. If None, sequences are
                generated from learned weight parameters.

        Returns:
            Tuple of:
                - sampled: One-hot nucleotide sequences ``(batch, 4, seq_length)``
                - mrl1: MRL prediction for full sequence ``(batch,)``
                - mrl2: MRL prediction from alt start ``(batch,)``
                - prot_f2: Amino acid sequence for downstream ORF
                  ``(batch, 21, aa_len)``
        """
        if input_onehot is None:
            weight = self.weight
            normed_left = self.layer_norm_left(weight[:, :, : self.alt_start])
            normed_right = self.layer_norm_right(weight[:, :, self.alt_start :])
            normed = torch.cat([normed_left, normed_right], dim=2)
            normed[:, :, self.right_end :] = (
                normed[:, :, self.right_end :] + (~self.right_overhang_mask).float() * self.mask_val
            )
            if self.seed_onehot is not None:
                seed = torch.log(self.seed_onehot + self.eps)
                normed_seed_left = self.layer_norm_seed_left(seed[:, :, : self.alt_start])
                normed_seed_right = self.layer_norm_seed_right(seed[:, :, self.alt_start :])
                normed_seed = torch.cat([normed_seed_left, normed_seed_right], dim=2)
                normed = normed + normed_seed
            sampled = self.stsampler(normed)
        else:
            sampled = input_onehot.clone()

        sampled[:, :, self.alt_start : (self.alt_start + 3)] = self.start_codon
        sampled_slice2 = sampled[:, :, self.alt_start :]
        withstop_slice2 = self.translator(sampled_slice2)
        prot_f2 = withstop_slice2[0][:, :, 1:]  # Skip start codon

        # Left-pad sequences to model_input_len for Optimus MRL prediction
        mrl1_input = F.pad(sampled, (self.model_input_len - self.seq_length, 0))
        mrl2_input = F.pad(
            sampled[:, :, : self.alt_start], (self.model_input_len - self.alt_start, 0)
        )
        mrl1 = self.model(mrl1_input, final_ind=0).squeeze(1)
        mrl2 = self.model(mrl2_input, final_ind=0).squeeze(1)

        return sampled, mrl1, mrl2, prot_f2
